Config = {}
Config.ESX = false 
Config.BotToken = "Your Bot Token"
Config.WebHook = "Your Discord WebHook"
Config.ChannelID = "Channel ID voor de Commands"
Config.ReplyUserName = "Bot Username"
Config.AvatarURL = "Bot Avatar URL"
Config.Prefix = "!"
Config.WaitEveryTick = 50 -- is in ms